name: sample demo for github actions
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, world!"
      - name: say multiple lines
        run: |
          echo "Hello, world!"
          echo "This is a multi-line command."
